heritages = ["Homesteader", "Trailfolk", "Industrialist", "Militant", "Urbanite", "Unseen", "Caravaneers"]

professions = ["Trapper", "Forager", "Stoneworker", "Carpenter", "Smelter", "Engineer", "Provisioner", "Trader", "Surgeon", "Physician", "Performer", "Artisan", "None"]

inventory_items = [
    "Dollars",
    "Animal Carcass (S)",
    "Animal Carcass (M)",
    "Animal Carcass (L)",
    "Animal Skin (S)",
    "Animal Skin (M)",
    "Animal Skin (L)",
    "Sinew(s)",
    "Feathers",
    "Wild Herbs",
    "Medicinal Roots",
    "Berries (Edible)",
    "Berries (Poison)",
    "Wild Fibers (Grasses)",
    "Loose Stone",
    "Common Ore Fragment",
    "Uncut Gem",
    "Raw Quartz",
    "Logs",
    "Branches",
    "Pitch/Sap",
    "Niter",
    "Fresh Bandage",
    "Classic Revolver",
    "Classic Rifle",
    "Lead Bullets",
    "Basic Melee Weapon",
    "Large Game Trap",
    "Carcass Bag",
    "Skinning Knife",
    "Farmer's Spade",
    "Forager's Satchel",
    "Land-Farm Lease",
    "Simple Pickaxe",
    "Mining Log",
    "Stone Cutter's Chisel",
    "Lumberjack's Axe",
    "Woodworker's Tools",
    "Carpenter's Toolbox",
    "Smith's Hammer",
    "Smelting Crucible",
    "Anvil",
    "Gunsmith's Toolkit",
    "Firearm Maint. Kit",
    "Bullet Mold",
    "Butcher's Knife & Cleaver",
    "Cooking Pot & Still",
    "Salt Pouch",
    "Market Ledger",
    "Lap Desk & Ink Pen",
    "Merchant's Loupe",
    "Chart & Stethescope",
    "Surgical Kit",
    "Mortar & Pestle",
    "Observation Journal",
    "Reference Tomes",
    "Pocket Watch",
    "Little Black Book",
    "Performer Instrument",
    "Cutpurse Knife",
    "Alchemical Tools",
    "Tome of Symbology",
    "Simple Bow",
    "Arrows",
    "Ore / Metal Ingot",
    "Small Parts Kit",
    "Box of Bullets",
    "Box of Casings",
    "Glass",
    "Glass Bottle",
    "Stitcher's Salve",
    "Lucky's Brew",
    "Smoked / Salted Carcass",
    "Fresh Game Meat"
]

CURRENCY_NAME = "Dollars"

profession_starting_items = {
    "Trapper": ["Large Game Trap", "Skinning Knife", "Carcass Bag"],
    "Forager": ["Land-Farm Lease", "Farmer's Spade", "Forager's Satchel"],
    "Stoneworker": ["Mining Log", "Stone Cutter's Chisel", "Simple Pickaxe"],
    "Carpenter": ["Lumberjack's Axe", "Woodworker's Tools", "Carpenter's Toolbox"],
    "Smelter": ["Smith's Hammer", "Smelting Crucible", "Anvil"],
    "Engineer": ["Gunsmith's Toolkit", "Firearm Maint. Kit", "Bullet Mold",],
    "Provisioner": ["Butcher's Knife & Cleaver", "Cooking Pot & Still", "Salt Pouch"],
    "Trader": ["Market Ledger", "Lap Desk & Ink Pen", "Merchant's Loupe"],
    "Surgeon": ["Chart & Stethescope", "Surgical Kit", "Mortar & Pestle"],
    "Physician": ["Observation Journal", "Reference Tomes", "Pocket Watch"],
    "Performer": ["Little Black Book", "Performer Instrument", "Cutpurse Knife"],
    "Artisan": ["Alchemical Tools", "Tome of Symbology", "Forager's Satchel"],
    "None": []
}
